diary/urls.py
from django.views import generic
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('user/', views.DiaryList.as_view(), name='diary'),
    path('user/detail/<int:pk>/', views.DiaryDetail.as_view(), name='detail'),
    path('user/category/<int:pk>/', views.DiaryCategoryList.as_view(), name='category'),
    path('user/search/', views.DiarySearchList.as_view(), name='search'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('user/update/', views.UserUpdate.as_view(), name='user_update'),
    #path('user/<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
    #path('user/<int:pk>/profile/', views.UserDetail.as_view(), name='user_detail'),
    path('user/profile/', views.UserDetail.as_view(), name='user_detail'),
    path('user/<int:pk>/delete/', views.UserDelete.as_view(), name='user_delete'),
    path('user/post/', views.PostCreate.as_view(), name='post'),
    path('user/recommend/', views.RecommendList.as_view(), name='recommend'),
    path('user/recommend/detail/<int:pk>/', views.DiaryDetail.as_view(), name='recommend_detail'),
    #path('user/recommend/category/<int:pk>/', views.RecommendCategoryList.as_view(), name='recommend_category'),
    #path('user/recommend/search/', views.RecommendSearchList.as_view(), name='recommend_search'),
]

diary_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('diary.urls')),
    path('admin/', admin.site.urls),
]

diary/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.base_user import (
    AbstractBaseUser, BaseUserManager,
)
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# User-related
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class AbstractUser(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = True

    def __str__(self):
        return self.email

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"


class Category(models.Model):
    name = models.CharField('Category', max_length=255)

    def __str__(self):
        return self.name

class DiaryQuerySet(models.QuerySet):

    def published(self):
        return self.filter(created_at__lte=timezone.now())


class Writer(models.Model):
    name = models.CharField('Writer', max_length=255)

    def __str__(self):

        return self.name

class Diary(models.Model):
    title = models.CharField('Title', max_length=32)
    text = models.TextField('Contents')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Category')
    #category = models.CharField('Category', max_length=32, choices=CHOICE)
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='user')
    created_at = models.DateTimeField('Date', default=timezone.now)
    objects = DiaryQuerySet.as_manager()

    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Diary, Category, User


class DiarySearchForm(forms.Form):
    """検索フォーム。"""
    key_word = forms.CharField(
        label='Search',
        required=False,
    )

UserModel = get_user_model()

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['username'].widget.attrs['class'] = 'input'
       self.fields['password'].widget.attrs['class'] = 'input'

class UserCreateForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'

"""
class DiaryCreateForm(forms.Form):
    title = forms.CharField(
        label='Title',
        max_length=32,
        required=True,
    )
    category = forms.ModelChoiceField(
        label='Category',
        queryset=Category.objects.all(),
        required=True,
        empty_label='選択して下さい',
    )
    text = forms.CharField(
        label='Contents',
        widget=forms.Textarea,
        required=True,
    )
"""
"""
CHOICES = (
("request.POSTの中身", "画面に表示される内容"),
("0", "1000"),
("1", "2000"),
("2", "3000"),
("3", "4000"),
)
class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'text', 'category')
    category = forms.ChoiceField(
        widget=forms.Select,
        choices=CHOICES,
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'input'
"""

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'text', 'category')

    category = forms.ModelChoiceField(
        label='カテゴリ',
        queryset=Category.objects,
        #required=False
    )
    text = forms.CharField(
                widget=forms.Textarea(attrs={'class':'bulmatextarea'}))

diary/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.contrib.auth import get_user_model, login
from django.contrib.auth.views import (
    LoginView, LogoutView,
)
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import (
    CreateView, UpdateView, DeleteView,
)
from .mixins import OnlyYouMixin
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, DiaryCreateForm
)
from django.views import generic
from .models import Diary, Category, Writer
from django.utils import timezone
from django.http import Http404
from django.shortcuts import get_object_or_404, resolve_url
from django.db.models import Q
from .forms import DiarySearchForm
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

UserModel = get_user_model()

class TopView(LoginRequiredMixin, TemplateView):
    template_name = 'diary/top.html'

class Login(LoginView):
    form_class = LoginForm
    template_name = 'diary/login.html'

class Logout(LogoutView):
    template_name = 'diary/top.html'

class UserCreate(CreateView):
    form_class = UserCreateForm
    template_name = 'diary/signup.html'
    success_url = reverse_lazy('diary:diary')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())

@method_decorator(login_required, name='dispatch')
class UserUpdate(UpdateView):
    model = UserModel
    #form_class = UserUpdateForm
    fields = ('username', 'first_name', 'last_name', 'email')
    template_name = 'diary/user_update.html'
    success_url = reverse_lazy('diary:user_detail')

    def get_object(self):
        return self.request.user

@method_decorator(login_required, name='dispatch')
class UserDetail(TemplateView):
    #model = UserModel
    template_name = 'diary/user_detail.html'
    def get_queryset(self):
        return User.objects.get(user=self.request.user)

class UserDelete(OnlyYouMixin, DeleteView):
    model = UserModel
    template_name = 'diary/user_delete.html'
    success_url = reverse_lazy('diary:top')

"""
@login_required
def PostCreate(request):
    diary = Diary()
    diary.user = request.user
    if request.method == "POST":
        form = DiaryCreateForm(request.POST, instance=diary)
        if form.is_valid():
            diary = form.save(commit=False)
            diary.user = request.user
            diary.save()
        else:
            return render(request, 'diary/create.html', {'form': form})
    else:
        form = DiaryCreateForm(instance=diary)
    return render(request, 'diary/create.html', {'form': form})
"""
"""
@login_required
def PostCreate(request):
    template_name = 'diary/create.html'
    ctx = {}
    if request.method == 'GET':
        form = DiaryCreateForm()
        ctx['form'] = form
        return render(request, template_name, ctx)
    if request.method == 'POST':
        diary_form = DiaryCreateForm(request.POST)
        if diary_form.is_valid():
            diary = Diary()
            cleaned_data = diary_form.cleaned_data
            diary.title = cleaned_data['title']
            diary.text = cleaned_data['text']
            diary.user = request.user
            diary.category = cleaned_data['category']
            diary.save()
            return redirect(reverse_lazy('diary:diary'))
        else:
            ctx['form'] = diary_form
            return render(request, template_name, ctx)
"""

class PostCreate(generic.CreateView):
    template_name = 'diary/create.html'
    model = Diary
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary')

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

class ArchiveListMixin:
    model = Diary
    paginate_by = 10
    date_field = 'created_at'
    template_name = 'diary/mydiary.html'
    allow_empty = True
    make_object_list = True


class DiaryList(ArchiveListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        result = super().get_queryset().select_related('category')
        return result.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = 'Latest diary'
        #context['pk'] = self.kwargs['pk']
        return context

class DiaryDetail(generic.DetailView):
    model = Diary

    def get_object(self, queryset=None):
        diary = super().get_object()
        if diary.created_at <= timezone.now():
            return diary
        raise Http404

class DiaryCategoryList(ArchiveListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        self.category = category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return super().get_queryset().filter(category=category, user=self.request.user).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 Category Diary'.format(self.category.name)
        return context

class DiarySearchList(ArchiveListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        queryset = super().get_queryset().filter(user=self.request.user)
        self.request.form = form = DiarySearchForm(self.request.GET)
        form.is_valid()
        self.key_word = key_word = form.cleaned_data['key_word']
        if key_word:
            queryset = queryset.filter(Q(title__icontains=key_word) | Q(text__icontains=key_word))
        return queryset.select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 の検索結果'.format(self.key_word)
        return context

class RecommendListMixin:
    model = Diary
    paginate_by = 5
    date_field = 'created_at'
    template_name = 'diary/recommend.html'
    allow_empty = True
    make_object_list = True

class RecommendList(RecommendListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        result = super().get_queryset().select_related('category')
        user_diary = result.filter(user=self.request.user)
        other_diary = result.exclude(user=self.request.user)

        category_list = []

        for data in other_diary:
            category_list.append(data.category)
        category_list = list(set(category_list))

        for c in category_list:
            recommend_list = other_diary.filter(category=c)

        return recommend_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = 'Latest diary'
        #context['pk'] = self.kwargs['pk']
        return context

class RecommendCategoryList(RecommendListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        self.category = category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return super().get_queryset().filter(category=category, user=self.request.user).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 Category Diary'.format(self.category.name)
        return context

class RecommendSearchList(RecommendListMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        queryset = super().get_queryset().filter(user=self.request.user)
        self.request.form = form = DiarySearchForm(self.request.GET)
        form.is_valid()
        self.key_word = key_word = form.cleaned_data['key_word']
        if key_word:
            queryset = queryset.filter(Q(title__icontains=key_word) | Q(text__icontains=key_word))
        return queryset.select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 の検索結果'.format(self.key_word)
        return context

diary/templates/diary/base.html
{% load static %}
{% load diary %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block meta_title %}Diary{% endblock %}</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'materialize/css/materialize.min.css' %}" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'diary/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <meta name="description" content="{% block meta_description %}UTProjectSprint dialy_project{% endblock %}">
</head>


<body>
<header>
  <nav>
  	<div class="nav-wrapper white">
  		<div class="row">
  			<div class="col s12 z-depth-1 fixednav">
  				<a href="#" data-target="sidenav-2" class="left sidenav-trigger show-on-medium-and-up maincolor"><i class="material-icons">menu</i></a>
  			  <a href="#!" class="brand-logo center maincolor"><i class="material-icons maincolor">book</i>Diary</a>
          <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li><a class="maincolor" href="{% url 'diary:post' %}">Create new post</a></li>
            {% else %}
            <li><a class="waves-effect waves-light btn" href="{% url 'diary:signup' %}">Sign up</a></li>
            <li><a class="waves-effect waves-light btn" href="{% url 'diary:login' %}">Log in</a></li>
            {% endif %}
          </ul>
  			</div>
  		</div>
		</div>
  </nav>
</header>

<!--デスクトップ用-->
<ul id="sidenav-2" class="sidenav">
    <li><div class="user-view">
      <div class="background backcolor">
      </div>
      <a href="{% url 'diary:user_detail' %}"><i class="material-icons maincolor">person</i></a>
      <a href="{% url 'diary:user_detail' %}"><span class="white-text name maincolor">{{ user.username }}</span></a>
      <a href="{% url 'diary:user_detail' %}"><span class="white-text email maincolor">{{ user.email }}</span></a>
    </div></li>

    {% render_search_form request %}

    <li><div class="divider"></div></li>

    <li><a class="subheader">Menu</a></li>
      <li><a href="{% url 'diary:diary' %}">MyDiary</a></li>
      <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Category<i class="material-icons right">arrow_drop_down</i></a></li>
      <li><a href="{% url 'diary:recommend' %}">Recommend</a></li>
      <li><a href="{% url 'diary:logout' %}">Log out</a></li>
  </ul>
<ul id="dropdown1" class="dropdown-content">
  {% render_category_links %}
</ul>

{% for field, errors in form.errors.items %}
    <article class="message is-warning">
        <div class="message-body">
        {% for error in errors %}
            <p><strong>{{ error }}</strong></p>
        {% endfor %}
        </div>
    </article>
{% endfor %}

<div class="fixed-action-btn hide-on-large-only">
  <a class="btn-floating btn-large" href="{% url 'diary:post' %}">
    <i class="large material-icons btncolor">mode_edit</i>
  </a>
</div>


<main>
  {% block content %}{% endblock %}
</main>

<footer class="page-footer white">
  <div class="footer-copyright">
    <div class="container center grey-text text-darken-2">
    Made by <a class="maincolor" >tm-017</a>
    </div>
  </div>
</footer>

<!--JavaScript at end of body for optimized loading-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
<script src="{% static 'materialize/js/init.js' %}"></script>
<script src="{% static 'diary/script.js' %}"></script>
</body>
</html>

diary/templates/diary/login.html
{% extends 'diary/simple_base.html' %}

{% block title %}Login | {% endblock %}

{% block content %}
<br><br>
<section class="section">
    <div class="card logcard">
      <div class="container">
        <span class="login100-form-title p-t-50 p-b-51">Login</span>
          <br>
          <form method="post" action="">
              {% csrf_token %}
              <div class="field">
                  <label class="label">Username</label>
                  <div class="control has-icons-left">
                      {{ form.username }}
                      <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                  </div>
              </div>
              <div class="field">
                  <label class="label">Password</label>
                  <div class="control has-icons-left">
                      {{ form.password }}
                      <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                  </div>
              </div>
              <div class="field center p-t-50">
                  <p class="control">
                      <input type="submit" value="LOGIN" class="is-success waves-effect waves-teal btn-flat btncolor">
                      <input type="hidden" name="next" value="{{ next }}" >
                  </p>
              </div>
              <p class="help center p-b-51"><a href="{% url 'diary:signup' %}">Sign up</a></p>
          </form>
      </div>
    </div>
</section>
{% endblock %}

diary/templates/diary/mydiary.html
{% extends "diary/base.html" %}
{% load diary %}

{% block meta_title %}{{ heading }} - {{ block.super }}{% endblock %}

{% block content %}
<br><br>
<section id="diary-list" class="container">
  {% for diary in object_list %}
  <ul class="collapsible expandable popout">
    <li>
      <div class="collapsible-header">
        {{ diary.title }}
        <time class = "right grey-text text-darken-1" datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y/n/j' }}</time>
      </div>
      <div class="collapsible-body">
        <!--<a href="{% url 'diary:detail' diary.pk %}"> -->
        <div class="tag maincolor">{{ diary.category }}</div>
        <br>
        <div class="contents">
          {{ diary.text | truncatechars:100 }}
        </div>
        <!--</a>-->
      </div>
    </li>
    </ul>
  {% empty %}

    <p>記事が見つかりませんでした。</p>

  {% endfor %}
  <br><br>

  <ul class="pagination center">
    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true"><i class="material-icons">chevron_left</i></span>
            </a>
        </li>
    {% else %}
        <li class="disabled"><a><i class="material-icons">chevron_left</i></a></li>
    {% endif %}

    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <i class="material-icons">chevron_right</i>
            </a>
        </li>
    {% else %}
        <li class="disabled"><a><i class="material-icons">chevron_right</i></a></li>
    {% endif %}
</ul>

</section>

{% endblock %}

diary/templates/diary/recommend.html
{% extends "diary/base.html" %}
{% load diary %}

{% block meta_title %}{{ heading }} - {{ block.super }}{% endblock %}

{% block content %}
<br><br>
<section id="diary-list" class="container">
  {% for diary in object_list %}
  <ul class="collapsible expandable popout">
    <li>
      <div class="collapsible-header">
        {{ diary.title }}
        <time class = "right grey-text text-darken-1" datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y/n/j' }}</time>
      </div>
      <div class="collapsible-body">
        <!--<a href="{% url 'diary:detail' diary.pk %}"> -->
        <div class="tag maincolor">{{ diary.category }}</div>
        <br>
        <div class="contents">
          {{ diary.text | truncatechars:100 }}
        </div>
        <!--</a>-->
      </div>
    </li>
    </ul>
  {% empty %}

    <p>記事が見つかりませんでした。</p>

  {% endfor %}
  <br><br>

  <ul class="pagination center">
    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true"><i class="material-icons">chevron_left</i></span>
            </a>
        </li>
    {% else %}
        <li class="disabled"><a><i class="material-icons">chevron_left</i></a></li>
    {% endif %}

    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <i class="material-icons">chevron_right</i>
            </a>
        </li>
    {% else %}
        <li class="disabled"><a><i class="material-icons">chevron_right</i></a></li>
    {% endif %}
</ul>

</section>

{% endblock %}

diary/templates/diary/signup.html
{% extends 'diary/simple_base.html' %}

{% block title %}Signup | {% endblock %}

{% block content %}
<br><br>
<section class="section">
    <div class="card logcard">
      <div class="container">
        <span class="login100-form-title p-t-50 p-b-51">Sign up</span>
          <br>
          <form method="post" action="">
              {% csrf_token %}
              <div class="field">
                  <label class="label">Username</label>
                  <div class="control has-icons-left">
                      {{ form.username }}
                      <span class="icon is-small is-left"><i class="fas fa-user"></i></span>
                  </div>
              </div>
              <div class="field">
                  <label class="label">e-mail</label>
                  <div class="control has-icons-left">
                      {{ form.email }}
                      <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                  </div>
              </div>
              <div class="field">
                  <label class="label">Password</label>
                  <div class="control has-icons-left">
                      {{ form.password1 }}
                      <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                  </div>
              </div>
              <div class="field">
                  <label class="label">Retype Password</label>
                  <div class="control has-icons-left">
                      {{ form.password2 }}
                      <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                  </div>
              </div>
              <div class="field center p-t-50">
                  <p class="control">
                      <input type="submit" value="SIGN UP" class="button is-success waves-effect waves-teal btn-flat btncolor">
                      <input type="hidden" name="next" value="{{ next }}" >
                  </p>
              </div>
              <p class="help center p-b-51"><a href="{% url 'diary:login' %}">Login</a></p>
          </form>
      </div>
    </div>
</section>
{% endblock %}

diary/templates/diary/top.html
{% extends "diary/top_base.html" %}
{% load diary %}

{% block meta_title %}{{ heading }} - {{ block.super }}{% endblock %}

{% block content %}
<div class="wrapper">
  <div class="column page1">
      <div class="position-absolute">
          <div class="p-t-b-15" style="margin-top: 70px;">
            <i class="material-icons white-text">create</i><span class="white-text" style="margin-left: 20px;font-size: 20px;">日記を書きましょう。</span>
          </div>
          <div class="p-t-b-15">
            <i class="material-icons white-text">group</i><span class="white-text" style="margin-left: 20px;font-size: 20px;">他の人の生活を参考にしましょう。</span>
          </div>
          <div class="p-t-b-15">
            <i class="material-icons white-text">trending_up</i><span class="white-text" style="margin-left: 20px;font-size: 20px;">あなたの生活を向上させましょう。</span>
          </div>
      </div>
    </div>
  <div class="column page2">
    <div class="container">
      <div style="margin-top: 50%;">
        <div class="p-t-b-15">
          <span class="maincolor center" style="font-size: 35px;display: grid;">日記を共有しましょう</span>
        </div>
        <br>
        <div class="row center">
          <a href="{% url 'diary:signup' %}" id="download-button" class="waves-effect waves-teal btn-flat btncolor white-text" style="width: 200px;">Sign up</a>
        </div>
        <div class="row center">
          <a href="{% url 'diary:login' %}" id="download-button" class="waves-effect waves-teal btn-flat btncolor white-text" style="width: 200px;">Log in</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}